# Generated by Django 5.1.7 on 2025-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='accreditation_docs/', verbose_name='Файл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Документ аккредитации',
                'verbose_name_plural': 'Документы аккредитации',
                'ordering': ['order'],
            },
        ),
    ]
